package com.peykasa.sdp.services.compositesmsgateway.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-02T23:15:28.300Z
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "CompositeSmsGatewayService", 
                  wsdlLocation = "http://ws.asanak.ir:8082/services/CompositeSmsGateway?wsdl",
                  targetNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/") 
public class CompositeSmsGatewayService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.compositeSmsGateway.services.sdp.peykasa.com/", "CompositeSmsGatewayService");
    public final static QName CompositeSmsGateway = new QName("http://webService.compositeSmsGateway.services.sdp.peykasa.com/", "CompositeSmsGateway");
    static {
        URL url = null;
        try {
            url = new URL("http://ws.asanak.ir:8082/services/CompositeSmsGateway?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CompositeSmsGatewayService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ws.asanak.ir:8082/services/CompositeSmsGateway?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CompositeSmsGatewayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CompositeSmsGatewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompositeSmsGatewayService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CompositeSmsGatewayService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CompositeSmsGatewayService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CompositeSmsGatewayService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CompositeSmsGateway
     */
    @WebEndpoint(name = "CompositeSmsGateway")
    public CompositeSmsGateway getCompositeSmsGateway() {
        return super.getPort(CompositeSmsGateway, CompositeSmsGateway.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompositeSmsGateway
     */
    @WebEndpoint(name = "CompositeSmsGateway")
    public CompositeSmsGateway getCompositeSmsGateway(WebServiceFeature... features) {
        return super.getPort(CompositeSmsGateway, CompositeSmsGateway.class, features);
    }

}
